### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Trolann** [HarvsG/gli_py#1]
Appears the API is no longer exposed and you need to use RPC now. Is this still maintained? Considering forking but looks like the entire API has changed.

**Comment by HarvsG** [comment]
https://github.com/HarvsG/gli4py

**Comment by Trolann** [comment]
Perfect! I'll fork it and see what I can do.

**Comment by HarvsG** [comment]
Cool, can you link to details about this new RPC API? 
I think that openWRT supports an RPC API and so GL inet hardware probably also supports the same.

**Comment by Trolann** [comment]
[API 4.0 login.pdf](https://github.com/user-attachments/files/16041932/API.4.0.login.pdf)
[API 4.0 mcu.pdf](https://github.com/user-attachments/files/16041933/API.4.0.mcu.pdf)
[API 4.0 system.pdf](https://github.com/user-attachments/files/16041934/API.4.0.system.pdf)

I'm in talks with GL Inet now, and getting these docs via email. I've asked about an endpoint that allows enumeration, but it's the weekend now so it'll be a few days. Honestly I thought you had these because the login code is almost copy/pasted.

I have found on the router itself the nginx and lua configs and it looks like there may not be a `ubus list` equivalent. My goal was similar to [python-ubus](https://github.com/rytilahti/python-ubus/blob/master/src/ubus/protocol.py) but without enumeration I'd just have to hard code the routes. Not the end of the world, but I'd rather look at hard coding in the integration for HA and then abstract everything available for further dev work.

**Comment by HarvsG** [comment]
They used to host the API docs here. Although I found the quality of the documentation to be quite variable and the return codes quite unpredictable.

https://dev.gl-inet.com/router-4.x-api/

**Comment by HarvsG** [comment]
Moved discussion to https://github.com/HarvsG/gli4py/issues/1
